app:
    command: npm start
    environment:
        - NODE_ENV=production
    expose:
        - '3000'
    image: 'justinlivi/justinlivi.com:latest'
    target_num_containers: 2

lb:
    image: 'dockercloud/haproxy:latest'
    links:
        - app
    environment:
        - 'CERT_FOLDER=/etc/letsencrypt/justinlivi.com'
    ports:
        - '80:80'
        - '443:443'
